apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-deployment
  labels:
    app: frontend-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: saurabh7nt/microservice-frontend-service:v8
        ports:
          - containerPort: 80
