apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service

spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: saurabh7nt/microservice-order-service:v3
        ports:
          - containerPort: 8083
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-db-svc:5432/microservices_db"
          - name: SPRING_DATASOURCE_USERNAME
            value: "admin"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "admin123"
          - name: SPRING_JPA_OPEN_IN_VIEW
            value: "false"
          - name: CORS_ALLOWED_ORIGINS
            value: "http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
