apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service
  ports:
    - name: order-service-port
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
