name: order-service-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/order-service/**'
      - 'backend/common/**'
      - 'backend/pom.xml'

  pull_request:
    paths:
      - 'backend/order-service/**'
      - 'backend/common/**'
      - 'backend/pom.xml'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout required code files
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            backend/order-service
            backend/common
            backend/pom.xml

      - name: Verify structure
        run: ls -R

      - name: Build service
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          echo "Printing mvn version.."
          mvn --version
          echo "Printing java version.."
          java --version

